# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(default=1, help_text='select an ingredient from the list or add a new one', on_delete=django.db.models.deletion.CASCADE, to='recipe.Ingredient'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='measurement',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='measurement',
            field=models.ForeignKey(blank=True, help_text='Select a type of measurement or add one (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Measurement'),
        ),
    ]
