# Generated by Django 3.0.5 on 2020-06-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20200502_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(blank=True, help_text='Amount of an ingredient needed for recipe', null=True),
        ),
    ]
