# Generated by Django 3.0.5 on 2020-06-01 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20200601_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name of an ingredient', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A description (optional)', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(blank=True, help_text='Amount of an ingredient needed for recipe', null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement',
            field=models.ForeignKey(blank=True, help_text='Select a type of measurement or add one (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe.Measurement'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='select or add an ingredient with measurement', to='recipe.Ingredient'),
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Select an ingredient from the list or add a new one', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe.Product'),
        ),
    ]
